name: "security-checkpoint"
description: "Check for vulnerabilities in go and node apps"
inputs:
  manager:
    description: "which auditing system to use based on package manager (e.g. go, npm)"
    required: true
    default: "."
runs:
  using: composite
  steps:
    - name: "run script"
      shell: bash
      run: ${{ github.action_path }}/security.sh
      env:
        PACKAGE_MANAGER: ${{ inputs.manager }}